### ISSUE TITLE
Wrong thermometer tile format

### ISSUE THREAD

**Issue by fmikulu** [logimic/gateway-dashboard#2]
![000152](https://user-images.githubusercontent.com/17859927/46659176-b968b900-cbb4-11e8-9a5a-4b4c75903742.png)

Possible solution:
- round off to one decimal digit and print in fixed format with one decimal place (even with .0): 26.0 °C
- downsize font to fit whole temperature value in one line

**Comment by MichalValny** [comment]
solved 76f62799e62d785b8114c29a089bc763e1f61b21
