### ISSUE TITLE
Better tile formatting

### ISSUE THREAD

**Issue by fmikulu** [logimic/gateway-dashboard#3]
- Round off to max 3 decimal places.
- Scale label font to fit tile.
- move value upper
- consider 3 lines
  - value
  - unit (may be smaller font then value)
  - label (wrap to tile to more lines?)

![000183](https://user-images.githubusercontent.com/17859927/52998888-a8fb0180-3424-11e9-9ffe-b38f924e07fa.png)

**Comment by MichalValny** [comment]
c8e7507a2ed94c5f02611404709abb2173973156
